

START_ADDR EQU 2002H
BLOCK_SIZE EQU 05H
INSERT_VAL EQU 55H


	   LXI H, START_ADDR + BLOCK_SIZE - 1
	   LXI D, START_ADDR + BLOCK_SIZE
	   MVI C, BLOCK_SIZE

SHIFT:	   MOV A,M	
	   STAX D		
	   DCX H		
	   DCX D		
	   DCR C		
	   JNZ SHIFT	
	   
	   LXI H,START_ADDR	
	   MVI M,INSERT_VAL	
	   HLT